### ISSUE TITLE
unexpected token "/"

### ISSUE THREAD

**Issue by scamaccas** [Wildan-dev461/NameSpacePreventJoin#1]
[Server thread/CRITICAL]: ParseError: "syntax error, unexpected token "/", expecting "{"" (EXCEPTION) in "plugins/NameSpacePreventJoin/src/Wildan/NoSpace/Main" at line 5

**Comment by Wildan-dev461** [comment]
> [Server thread/CRITICAL]: ParseError: "syntax error, unexpected token "/", expecting "{"" (EXCEPTION) in "plugins/NameSpacePreventJoin/src/Wildan/NoSpace/Main" at line 5

why u closed? did the error still exist?

**Comment by scamaccas** [comment]
i fix the namespace 😄
